spring.application.name=dream-shops


spring.datasource.url = jdbc:postgresql://localhost:5432/dream_shops_db
spring.datasource.username = postgres
spring.datasource.password = 0000


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Hibernate will change different sql syntax based on different database

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Automatic create, update, create-drop, validate database table
spring.jpa.hibernate.ddl-auto=update
# make sure your change to update so that the data in database will not lose
# create make the database refresh

spring.servlet.multipart.max-file-size = 5MB
spring.servlet.multipart.max-request-size = 5MB

api.prefix=/api/v1

auth.token.expirationInMils = 3600000
# 3600000 (60 * 60 * 1000 ms) = 1 HR
auth.token.jwtSecret=36763979244226452948404D635166546A576D5A7134743777217A25432A462D



